### ISSUE TITLE
Incorrect contig identifiers

### ISSUE THREAD

**Issue by rsuchecki** [CroBiAd/potage_data#1]
It appears that in the blast database the 4AL contig ids have "4AL_" prepended twice, e.g. 	4AL_4AL_7118584 so they can't be found in POTAGE tables

![image](https://cloud.githubusercontent.com/assets/5534231/21391287/ff6fd4e0-c7da-11e6-8bd5-875b1ef2c8cf.png)

**Comment by nathanhaigh** [comment]
It's also 4DL contigs too!

For these 2 files, it's probably a problem with the files I updated to NeCTAR object storage! I may have uploaded the ones with modified ID lines instead of the original files from URGI.

**Comment by nathanhaigh** [comment]
Nope, the URGI files for 4AL and 4DL already have the chr arm prefixes.

**Comment by nathanhaigh** [comment]
@rsuchecki Docker Hub auto build is running can you check it's fixed and mark this resolved/closed if you get a chance once the public server has updated (in 15 min or so).
